name: flutter_chat_app_challenge
description: A new Flutter UI Challenge.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-126.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf
        - asset: fonts/Metropolis-Light.otf
        - asset: fonts/Metropolis-Medium.otf
        - asset: fonts/Metropolis-Black.otf
